export const WEBM_ELEMENT_IDS = Object.freeze({
    SEGMENT: 0x18538067,
    INFO: 0x1549a966,
    TIMECODE_SCALE: 0x2ad7b1,
    DURATION: 0x4489,

    TRACKS: 0x1654ae6b,
    TRACK_ENTRY: 0xae,
    TRACK_NUMBER: 0xd7,
    TRACK_TYPE: 0x83,
    CODEC_ID: 0x86,
    CODEC_PRIVATE: 0x63a2,
    VIDEO: 0xe0,
    AUDIO: 0xe1,
    PIXEL_WIDTH: 0xb0,
    PIXEL_HEIGHT: 0xba,
    SAMPLING_FREQUENCY: 0xb5,
    CHANNELS: 0x9f,

    CLUSTER: 0x1f43b675,
    CLUSTER_TIMECODE: 0xe7,
    SIMPLE_BLOCK: 0xa3,
    BLOCK_GROUP: 0xa0,
    BLOCK: 0xa1,
    BLOCK_GROUP_REFERENCE_BLOCK: 0xfb,
    BLOCK_GROUP_KEYFRAME: 0x9b
});

export const WEBM_CONTAINER_ELEMENT_IDS = new Set([
    WEBM_ELEMENT_IDS.SEGMENT,
    WEBM_ELEMENT_IDS.INFO,
    WEBM_ELEMENT_IDS.TRACKS,
    WEBM_ELEMENT_IDS.TRACK_ENTRY,
    WEBM_ELEMENT_IDS.VIDEO,
    WEBM_ELEMENT_IDS.AUDIO,
    WEBM_ELEMENT_IDS.CLUSTER,
    WEBM_ELEMENT_IDS.BLOCK_GROUP
]);
